# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161125_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
