# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161126_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
