# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 17:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20161126_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_num', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('hit', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Board')),
                ('subject', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='board',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='author',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='board',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
